### ISSUE TITLE
undefined method `page_path' for #<#<Class:0x000000032b49b0> [Nested Routes Handling Issue]

### ISSUE THREAD

**Issue by taimoor** [the-teacher/the_sortable_tree#38]
Note: It seems that new gem version is burst out with nested routes. Kindly guide me the way to get rid of it. 

I've upgraded to rails 3.2.13 using your gem version 2.3.2.

I've pages controller and used nested route for it '/hotels/:hotel_id/pages/new'. It was working fine in rails 3.1.11 and your gem version 1.8.0 but now in view html.erb file it gives me error.

NoMethodError - undefined method `page_path' for #<#<Class:0x000000032b49b0>:0x007f5d8c09f830>:
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/polymorphic_routes.rb:129:in`polymorphic_url'
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/polymorphic_routes.rb:135:in `polymorphic_path'
  (gem) actionpack-3.2.13/lib/action_view/helpers/url_helper.rb:111:in`url_for'
  (gem) the_sortable_tree-2.3.2/app/helpers/render_sortable_tree_helper.rb:34:in `show_link'
  (gem) the_sortable_tree-2.3.2/app/helpers/render_sortable_tree_helper.rb:23:in`render_node'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:29:in `build_tree_html'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:127:in`build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:123:in `block in build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:121:in`build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:123:in `block in build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:121:in`build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:123:in `block in build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:121:in`build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:123:in `block in build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:121:in`build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:111:in `block in build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:109:in`build_server_tree'
  (gem) the_sortable_tree-2.3.2/app/helpers/the_sortable_tree_helper.rb:41:in `sortable_tree'
  app/views/pages/index.html.erb:9:in`_app_views_pages_index_html_erb__1838514784977886306_70019879107800'
  (gem) actionpack-3.2.13/lib/action_view/template.rb:145:in `block in render'
  (gem) activesupport-3.2.13/lib/active_support/notifications.rb:125:in`instrument'
  (gem) actionpack-3.2.13/lib/action_view/template.rb:143:in `render'
  (gem) actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:47:in`block (2 levels) in render_template'
  (gem) actionpack-3.2.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  (gem) activesupport-3.2.13/lib/active_support/notifications.rb:123:in`block in instrument'
  (gem) activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  (gem) activesupport-3.2.13/lib/active_support/notifications.rb:123:in`instrument'
  (gem) actionpack-3.2.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  (gem) actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:46:in`block in render_template'
  (gem) actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  (gem) actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:45:in`render_template'
  (gem) actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:18:in `render'
  (gem) actionpack-3.2.13/lib/action_view/renderer/renderer.rb:36:in`render_template'
  (gem) actionpack-3.2.13/lib/action_view/renderer/renderer.rb:17:in `render'
  (gem) actionpack-3.2.13/lib/abstract_controller/rendering.rb:110:in`_render_template'
  (gem) actionpack-3.2.13/lib/action_controller/metal/streaming.rb:225:in `_render_template'
  (gem) actionpack-3.2.13/lib/abstract_controller/rendering.rb:103:in`render_to_body'
  (gem) actionpack-3.2.13/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  (gem) actionpack-3.2.13/lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  (gem) actionpack-3.2.13/lib/abstract_controller/rendering.rb:88:in `render'
  (gem) actionpack-3.2.13/lib/action_controller/metal/rendering.rb:16:in`render'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  (gem) activesupport-3.2.13/lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
  /home/coeus/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  (gem) activesupport-3.2.13/lib/active_support/core_ext/benchmark.rb:5:in`ms'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  (gem) activerecord-3.2.13/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:39:in`render'
  (gem) remotipart-1.0.5/lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
  (gem) actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:10:in`default_render'
  (gem) actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  (gem) actionpack-3.2.13/lib/abstract_controller/base.rb:167:in`process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
  (gem) actionpack-3.2.13/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:447:in `_run__3561563905337554102__process_action__2161468695265538341__callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`__run_callback'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:81:in`run_callbacks'
  (gem) actionpack-3.2.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/rescue.rb:29:in`process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  (gem) activesupport-3.2.13/lib/active_support/notifications.rb:123:in`block in instrument'
  (gem) activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  (gem) activesupport-3.2.13/lib/active_support/notifications.rb:123:in`instrument'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  (gem) activerecord-3.2.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  (gem) actionpack-3.2.13/lib/abstract_controller/base.rb:121:in`process'
  (gem) actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
  (gem) actionpack-3.2.13/lib/action_controller/metal.rb:203:in`dispatch'
  (gem) actionpack-3.2.13/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  (gem) actionpack-3.2.13/lib/action_controller/metal.rb:246:in`block in action'
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:36:in`call'
  (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
  (gem) omniauth-1.1.4/lib/omniauth/strategy.rb:184:in`call!'
  (gem) omniauth-1.1.4/lib/omniauth/strategy.rb:164:in `call'
  (gem) omniauth-1.1.4/lib/omniauth/strategy.rb:184:in`call!'
  (gem) omniauth-1.1.4/lib/omniauth/strategy.rb:164:in `call'
  (gem) warden-1.2.1/lib/warden/manager.rb:35:in`block in call'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  (gem) rack-1.4.5/lib/rack/etag.rb:23:in `call'
  (gem) rack-1.4.5/lib/rack/conditionalget.rb:25:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/head.rb:14:in `call'
  (gem) remotipart-1.0.5/lib/remotipart/middleware.rb:30:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/flash.rb:242:in`call'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:205:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  (gem) activerecord-3.2.13/lib/active_record/query_cache.rb:64:in`call'
  (gem) activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `_run__1903898215360380510__call__623521404916346025__callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`__run_callback'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:81:in`run_callbacks'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:65:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  (gem) better_errors-0.8.0/lib/better_errors/middleware.rb:84:in`protected_app_call'
  (gem) better_errors-0.8.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
  (gem) better_errors-0.8.0/lib/better_errors/middleware.rb:56:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  (gem) railties-3.2.13/lib/rails/rack/logger.rb:32:in `call_app'
  (gem) railties-3.2.13/lib/rails/rack/logger.rb:16:in`block in call'
  (gem) activesupport-3.2.13/lib/active_support/tagged_logging.rb:22:in `tagged'
  (gem) railties-3.2.13/lib/rails/rack/logger.rb:16:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  (gem) rack-1.4.5/lib/rack/methodoverride.rb:21:in`call'
  (gem) rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  (gem) activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  (gem) rack-1.4.5/lib/rack/lock.rb:15:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/static.rb:63:in`call'
  (gem) railties-3.2.13/lib/rails/engine.rb:479:in `call'
  (gem) railties-3.2.13/lib/rails/application.rb:223:in`call'
  (gem) rack-1.4.5/lib/rack/content_length.rb:14:in `call'
  (gem) railties-3.2.13/lib/rails/rack/log_tailer.rb:17:in`call'
  (gem) rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
  /home/coeus/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/coeus/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/coeus/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'
